resources:
  - name: springconcoursetestGit
    type: git
    source:
      uri: https://github.com/SkyChanger/SpringBoot-ConcourseCI.git
      branch: master
  - name: time
    type: time
    source:
      interval: 10s

jobs:
  - name: Build Spring Concourse Test
    public: true
    plan:
    - get:  springconcoursetestGit
      triggered: true
    - task: package
      privileged: true
      file: SpringBoot-ConcourseCI/pipeline/ci/concourse.yml